// packages/react/src/index.ts
import { renderMathMLBody } from "mmtypst";
import type { RenderMathMLBodyOptions } from "mmtypst";
import { createElement } from "react";
import type { HTMLAttributes, ReactElement, Ref } from "react";

export interface MathProps
  extends
    Omit<HTMLAttributes<MathMLElement>, "children" | "dangerouslySetInnerHTML" | "display">,
    RenderMathMLBodyOptions {
  /** Typst math expression without its surrounding `$` delimiters. */
  source: string;
  /** Ref to the rendered MathML element. */
  ref?: Ref<MathMLElement>;
}

/** Renders a Typst math expression as a native MathML element. */
export function Math({
  source,
  display = "inline",
  throwOnError,
  symbols,
  ref,
  ...mathProps
}: MathProps): ReactElement {
  const markup = {
    __html: renderMathMLBody(source, { display, throwOnError, symbols }),
  };

  return createElement("math", {
    ...mathProps,
    ref,
    xmlns: "http://www.w3.org/1998/Math/MathML",
    display,
    dangerouslySetInnerHTML: markup,
  });
}

// packages/solid/src/index.tsx
import { renderMathMLBody } from "mmtypst";
import type { RenderMathMLBodyOptions } from "mmtypst";
import { createMemo, splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface MathProps
  extends
    Omit<
      JSX.IntrinsicElements["math"],
      "children" | "innerHTML" | "innerText" | "textContent" | "display"
    >,
    RenderMathMLBodyOptions {
  /** Typst math expression without its surrounding `$` delimiters. */
  source: string;
}

/** Renders a Typst math expression as a native MathML element. */
export function Math(props: MathProps): JSX.Element {
  const [options, mathProps] = splitProps(props, ["source", "display", "throwOnError", "symbols"]);
  const body = createMemo(() =>
    renderMathMLBody(options.source, {
      display: options.display,
      throwOnError: options.throwOnError,
      symbols: options.symbols,
    }),
  );

  return (
    <math
      {...mathProps}
      xmlns="http://www.w3.org/1998/Math/MathML"
      display={options.display ?? "inline"}
      innerHTML={body()}
    />
  );
}
